---
title: "JuneInterruption"
output:
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float: true
---

```{r setup}
# Load packages
library(tidyverse)
library(ggplot2) 
library(readxl) 
library(lubridate)
library(broom)
library(viridis)
library(tsModel)
library(scales)
library(grid) 
library(tseries) 
library(tsibble) 
library(fable)
library(feasts) 
library(forecast)

# Global options
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE) 
source("functions.R")

``` 

```{r import, include = FALSE}
monthly_f <- read.csv("../CleanData/monthly_f.csv") 
monthly_m <- read.csv("../CleanData/monthly_m.csv")

monthly_f <- monthly_f %>% 
  mutate(month_year = ymd(month_year))

monthly_m <- monthly_m %>% 
  mutate(month_year = ymd(month_year))

monthly_f.ts <- monthly_f %>% 
  mutate(month_year = ymd(month_year),
         month = yearmonth(month_year)) %>% 
  as_tsibble(index = month)
  
glimpse(monthly_f.ts) 

monthly_m.ts <- monthly_m %>% 
  mutate(month_year = ymd(month_year),
         month = yearmonth(month_year)) %>% 
  as_tsibble(index = month)
  
glimpse(monthly_m.ts)

``` 

```{r ACF_PACF, include = FALSE}
monthly_f.ts  |> #female
  gg_tsdisplay(y = Deaths, plot_type = "partial")

monthly_m.ts  |> #male
  gg_tsdisplay(y = Deaths, plot_type = "partial")
```


```{r}
# Create variable representing step and ramp changes
intervention_month <- monthly_f.ts %>% 
  filter(month_year == "2021-06-01") %>% 
  pull(time)

monthly_f.ts<- monthly_f.ts %>%
  mutate(
    t = row_number(),
    step = if_else(t >= intervention_month, 1, 0),
    ramp = if_else(t >= intervention_month, t - intervention_month + 1, 0)
  ) 

intervention_month <- monthly_m.ts %>% 
  filter(month_year == "2021-06-01") %>% 
  pull(time)

monthly_m.ts <- monthly_m.ts %>%
  mutate(
    t = row_number(),
    step = if_else(t >= intervention_month, 1, 0),
    ramp = if_else(t >= intervention_month, t - intervention_month + 1, 0)
  )

#View the step and ramp variables
monthly_f.ts %>%  #female
  pivot_longer(
    cols = c(step, ramp), 
    names_to = "variables",
    values_to = "value"
  ) %>%
  ggplot(aes(x = month_year, y = value, color = variables)) +
  geom_line(linewidth = 1) +
  geom_vline(
    xintercept = as.Date("2021-06-01"),
    linetype = "dashed",
    color = "black"
  ) +
  labs(
    title = "Step and Ramp Variables - Female",
    x = "Month",
    y = "Value",
    color = ""
  ) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme_minimal() 


monthly_m.ts %>% #male
  pivot_longer(
    cols = c(step, ramp), 
    names_to = "variables",
    values_to = "value"
  ) %>%
  ggplot(aes(x = month_year, y = value, color = variables)) +
  geom_line(linewidth = 1) +
  geom_vline(
    xintercept = as.Date("2021-06-01"),
    linetype = "dashed",
    color = "black"
  ) +
  labs(
    title = "Step and Ramp Variables - Male",
    x = "Month",
    y = "Value",
    color = ""
  ) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme_minimal() 

```
```